/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cognitio

import cognitio.matan.Polynomial
import java.math.BigDecimal.valueOf

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val name = ", man"
    println(App().greeting + name)
    val poly = Polynomial()
    poly.experiment()
    println(poly.y(valueOf(2)))
    println(poly.y(valueOf(3)))
    println(poly.y(valueOf(5)))
    println(poly.y(valueOf(4)))
}
